todoAgil-web/src/main/resources/cl/trello4/model/List.java
package cl.trello4.model;

/**
 * <code>
 * {
 * 	"id":"4e7b86d7ce194786721560b8",
 * 	"name":"Known Issues",
 * 	"closed":false,
 * 	"idBoard":"4d5ea62fd76aa1136000000c",
 * 	"pos":9408.2119140625
 * }
 * </code>
 * 
 * @author joel
 * 
 */
public class List extends TrelloObject {

	/** The name. */
	private String name;

	/** The closed. */
	private boolean closed;

	/** The id board. */
	private String idBoard;

	/** The pos. */
	private double pos;

	/**
	 * Gets the name.
	 * 
	 * @return the name
	 */
	public String getName() {
		return name;
	}

	/**
	 * Sets the name.
	 * 
	 * @param name
	 *            the new name
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * Checks if is closed.
	 * 
	 * @return true, if is closed
	 */
	public boolean isClosed() {
		return closed;
	}

	/**
	 * Sets the closed.
	 * 
	 * @param closed
	 *            the new closed
	 */
	public void setClosed(boolean closed) {
		this.closed = closed;
	}

	/**
	 * Gets the id board.
	 * 
	 * @return the id board
	 */
	public String getIdBoard() {
		return idBoard;
	}

	/**
	 * Sets the id board.
	 * 
	 * @param idBoard
	 *            the new id board
	 */
	public void setIdBoard(String idBoard) {
		this.idBoard = idBoard;
	}

	/**
	 * Gets the pos.
	 * 
	 * @return the pos
	 */
	public double getPos() {
		return pos;
	}

	/**
	 * Sets the pos.
	 * 
	 * @param pos
	 *            the new pos
	 */
	public void setPos(double pos) {
		this.pos = pos;
	}

}

todoAgil-web/src/main/java/managedbeans/AsignatureController.java
package managedbeans;

import cl.usach.diinf.todoagil.entities.Asignature;
import managedbeans.util.JsfUtil;
import managedbeans.util.JsfUtil.PersistAction;
import cl.usach.diinf.todoagil.facade.AsignatureFacadeLocal;

import java.io.Serializable;
import java.util.List;
import java.util.ResourceBundle;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.ejb.EJB;
import javax.ejb.EJBException;
import javax.inject.Named;
import javax.enterprise.context.SessionScoped;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.convert.Converter;
import javax.faces.convert.FacesConverter;

/**
 *
 * @author giovanni
 */
@Named("asignatureController")
@SessionScoped
public class AsignatureController implements Serializable {

    @EJB
    private cl.usach.diinf.todoagil.facade.AsignatureFacadeLocal ejbFacade;
    private List<Asignature> items = null;
    private Asignature selected;

    public AsignatureController() {
    }

    public Asignature getSelected() {
        return selected;
    }

    public void setSelected(Asignature selected) {
        this.selected = selected;
    }

    protected void setEmbeddableKeys() {
    }

    protected void initializeEmbeddableKey() {
    }

    private AsignatureFacadeLocal getFacade() {
        return ejbFacade;
    }

    public Asignature prepareCreate() {
        selected = new Asignature();
        initializeEmbeddableKey();
        return selected;
    }

    public void create() {
        persist(PersistAction.CREATE, ResourceBundle.getBundle("/Bundle").getString("AsignatureCreated"));
        if (!JsfUtil.isValidationFailed()) {
            items = null;    // Invalidate list of items to trigger re-query.
        }
    }

    public void update() {
        persist(PersistAction.UPDATE, ResourceBundle.getBundle("/Bundle").getString("AsignatureUpdated"));
    }

    public void destroy() {
        persist(PersistAction.DELETE, ResourceBundle.getBundle("/Bundle").getString("AsignatureDeleted"));
        if (!JsfUtil.isValidationFailed()) {
            selected = null; // Remove selection
            items = null;    // Invalidate list of items to trigger re-query.
        }
    }

    public List<Asignature> getItems() {
        if (items == null) {
            items = getFacade().findAll();
        }
        return items;
    }

    private void persist(PersistAction persistAction, String successMessage) {
        if (selected != null) {
            setEmbeddableKeys();
            try {
                if (persistAction != PersistAction.DELETE) {
                    getFacade().edit(selected);
                } else {
                    getFacade().remove(selected);
                }
                JsfUtil.addSuccessMessage(successMessage);
            } catch (EJBException ex) {
                String msg = "";
                Throwable cause = ex.getCause();
                if (cause != null) {
                    msg = cause.getLocalizedMessage();
                }
                if (msg.length() > 0) {
                    JsfUtil.addErrorMessage(msg);
                } else {
                    JsfUtil.addErrorMessage(ex, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
                }
            } catch (Exception ex) {
                Logger.getLogger(this.getClass().getName()).log(Level.SEVERE, null, ex);
                JsfUtil.addErrorMessage(ex, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
            }
        }
    }

    public Asignature getAsignature(java.lang.Integer id) {
        return getFacade().find(id);
    }

    public List<Asignature> getItemsAvailableSelectMany() {
        return getFacade().findAll();
    }

    public List<Asignature> getItemsAvailableSelectOne() {
        return getFacade().findAll();
    }

    @FacesConverter(forClass = Asignature.class)
    public static class AsignatureControllerConverter implements Converter {

        @Override
        public Object getAsObject(FacesContext facesContext, UIComponent component, String value) {
            if (value == null || value.length() == 0) {
                return null;
            }
            AsignatureController controller = (AsignatureController) facesContext.getApplication().getELResolver().
                    getValue(facesContext.getELContext(), null, "asignatureController");
            return controller.getAsignature(getKey(value));
        }

        java.lang.Integer getKey(String value) {
            java.lang.Integer key;
            key = Integer.valueOf(value);
            return key;
        }

        String getStringKey(java.lang.Integer value) {
            StringBuilder sb = new StringBuilder();
            sb.append(value);
            return sb.toString();
        }

        @Override
        public String getAsString(FacesContext facesContext, UIComponent component, Object object) {
            if (object == null) {
                return null;
            }
            if (object instanceof Asignature) {
                Asignature o = (Asignature) object;
                return getStringKey(o.getAsignatureId());
            } else {
                Logger.getLogger(this.getClass().getName()).log(Level.SEVERE, "object {0} is of type {1}; expected type: {2}", new Object[]{object, object.getClass().getName(), Asignature.class.getName()});
                return null;
            }
        }

    }

}

todoAgil-web/src/main/webapp/asignature/Create.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <ui:composition>

        <p:dialog id="AsignatureCreateDlg" widgetVar="AsignatureCreateDialog" modal="true" resizable="false" appendTo="@(body)" header="#{bundle.CreateAsignatureTitle}">
            <h:form id="AsignatureCreateForm">
                <h:panelGroup id="display">
                    <p:panelGrid columns="2" rendered="#{asignatureController.selected != null}">
                        <p:outputLabel value="#{bundle.CreateAsignatureLabel_asignatureId}" for="asignatureId" />
                        <p:inputText id="asignatureId" value="#{asignatureController.selected.asignatureId}" title="#{bundle.CreateAsignatureTitle_asignatureId}" required="true" requiredMessage="#{bundle.CreateAsignatureRequiredMessage_asignatureId}"/>
                        <p:outputLabel value="#{bundle.CreateAsignatureLabel_asignatureName}" for="asignatureName" />
                        <p:inputText id="asignatureName" value="#{asignatureController.selected.asignatureName}" title="#{bundle.CreateAsignatureTitle_asignatureName}" required="true" requiredMessage="#{bundle.CreateAsignatureRequiredMessage_asignatureName}"/>
                        <p:outputLabel value="#{bundle.CreateAsignatureLabel_asignatureTheoryHours}" for="asignatureTheoryHours" />
                        <p:inputText id="asignatureTheoryHours" value="#{asignatureController.selected.asignatureTheoryHours}" title="#{bundle.CreateAsignatureTitle_asignatureTheoryHours}" required="true" requiredMessage="#{bundle.CreateAsignatureRequiredMessage_asignatureTheoryHours}"/>
                        <p:outputLabel value="#{bundle.CreateAsignatureLabel_asignatureExercisesHours}" for="asignatureExercisesHours" />
                        <p:inputText id="asignatureExercisesHours" value="#{asignatureController.selected.asignatureExercisesHours}" title="#{bundle.CreateAsignatureTitle_asignatureExercisesHours}" required="true" requiredMessage="#{bundle.CreateAsignatureRequiredMessage_asignatureExercisesHours}"/>
                        <p:outputLabel value="#{bundle.CreateAsignatureLabel_asignatureLabHours}" for="asignatureLabHours" />
                        <p:inputText id="asignatureLabHours" value="#{asignatureController.selected.asignatureLabHours}" title="#{bundle.CreateAsignatureTitle_asignatureLabHours}" required="true" requiredMessage="#{bundle.CreateAsignatureRequiredMessage_asignatureLabHours}"/>
                        <p:outputLabel value="#{bundle.CreateAsignatureLabel_asignatureSemester}" for="asignatureSemester" />
                        <p:inputText id="asignatureSemester" value="#{asignatureController.selected.asignatureSemester}" title="#{bundle.CreateAsignatureTitle_asignatureSemester}" required="true" requiredMessage="#{bundle.CreateAsignatureRequiredMessage_asignatureSemester}"/>
                        <p:outputLabel value="#{bundle.CreateAsignatureLabel_asignatureYear}" for="asignatureYear" />
                        <p:inputText id="asignatureYear" value="#{asignatureController.selected.asignatureYear}" title="#{bundle.CreateAsignatureTitle_asignatureYear}" required="true" requiredMessage="#{bundle.CreateAsignatureRequiredMessage_asignatureYear}"/>
                        <p:outputLabel value="#{bundle.CreateAsignatureLabel_asignatureClose}" for="asignatureClose" />
                        <p:inputText id="asignatureClose" value="#{asignatureController.selected.asignatureClose}" title="#{bundle.CreateAsignatureTitle_asignatureClose}" required="true" requiredMessage="#{bundle.CreateAsignatureRequiredMessage_asignatureClose}"/>
                        <p:outputLabel value="#{bundle.CreateAsignatureLabel_userId}" for="userId" />
                        <p:selectOneMenu id="userId" value="#{asignatureController.selected.userId}" required="true" requiredMessage="#{bundle.EditAsignatureRequiredMessage_userId}">
                            <f:selectItems value="#{userController.itemsAvailableSelectOne}"
                                           var="userIdItem"
                                           itemValue="#{userIdItem}"/>
                        </p:selectOneMenu>
                        
                    </p:panelGrid>
                    <p:commandButton actionListener="#{asignatureController.create}" value="Guardar" update="display,:AsignatureListForm:datalist,:growl" oncomplete="handleSubmit(args,'AsignatureCreateDialog');"/>
                    <p:commandButton value="Cancelar" onclick="AsignatureCreateDialog.hide()"/>
                </h:panelGroup>
            </h:form>
        </p:dialog>

    </ui:composition>
</html>

todoAgil-web/src/main/webapp/asignature/Edit.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <ui:composition>

        <p:dialog id="AsignatureEditDlg" widgetVar="AsignatureEditDialog" modal="true" resizable="false" appendTo="@(body)" header="#{bundle.EditAsignatureTitle}">
            <h:form id="AsignatureEditForm">
                <h:panelGroup id="display">
                    <p:panelGrid columns="2" rendered="#{asignatureController.selected != null}">
                        <p:outputLabel value="#{bundle.EditAsignatureLabel_asignatureId}" for="asignatureId" />
                        <p:inputText id="asignatureId" value="#{asignatureController.selected.asignatureId}" title="#{bundle.EditAsignatureTitle_asignatureId}" required="true" requiredMessage="#{bundle.EditAsignatureRequiredMessage_asignatureId}"/>
                        <p:outputLabel value="#{bundle.EditAsignatureLabel_asignatureName}" for="asignatureName" />
                        <p:inputText id="asignatureName" value="#{asignatureController.selected.asignatureName}" title="#{bundle.EditAsignatureTitle_asignatureName}" required="true" requiredMessage="#{bundle.EditAsignatureRequiredMessage_asignatureName}"/>
                        <p:outputLabel value="#{bundle.EditAsignatureLabel_asignatureTheoryHours}" for="asignatureTheoryHours" />
                        <p:inputText id="asignatureTheoryHours" value="#{asignatureController.selected.asignatureTheoryHours}" title="#{bundle.EditAsignatureTitle_asignatureTheoryHours}" required="true" requiredMessage="#{bundle.EditAsignatureRequiredMessage_asignatureTheoryHours}"/>
                        <p:outputLabel value="#{bundle.EditAsignatureLabel_asignatureExercisesHours}" for="asignatureExercisesHours" />
                        <p:inputText id="asignatureExercisesHours" value="#{asignatureController.selected.asignatureExercisesHours}" title="#{bundle.EditAsignatureTitle_asignatureExercisesHours}" required="true" requiredMessage="#{bundle.EditAsignatureRequiredMessage_asignatureExercisesHours}"/>
                        <p:outputLabel value="#{bundle.EditAsignatureLabel_asignatureLabHours}" for="asignatureLabHours" />
                        <p:inputText id="asignatureLabHours" value="#{asignatureController.selected.asignatureLabHours}" title="#{bundle.EditAsignatureTitle_asignatureLabHours}" required="true" requiredMessage="#{bundle.EditAsignatureRequiredMessage_asignatureLabHours}"/>
                        <p:outputLabel value="#{bundle.EditAsignatureLabel_asignatureSemester}" for="asignatureSemester" />
                        <p:inputText id="asignatureSemester" value="#{asignatureController.selected.asignatureSemester}" title="#{bundle.EditAsignatureTitle_asignatureSemester}" required="true" requiredMessage="#{bundle.EditAsignatureRequiredMessage_asignatureSemester}"/>
                        <p:outputLabel value="#{bundle.EditAsignatureLabel_asignatureYear}" for="asignatureYear" />
                        <p:inputText id="asignatureYear" value="#{asignatureController.selected.asignatureYear}" title="#{bundle.EditAsignatureTitle_asignatureYear}" required="true" requiredMessage="#{bundle.EditAsignatureRequiredMessage_asignatureYear}"/>
                        <p:outputLabel value="#{bundle.EditAsignatureLabel_asignatureClose}" for="asignatureClose" />
                        <p:inputText id="asignatureClose" value="#{asignatureController.selected.asignatureClose}" title="#{bundle.EditAsignatureTitle_asignatureClose}" required="true" requiredMessage="#{bundle.EditAsignatureRequiredMessage_asignatureClose}"/>
                        <p:outputLabel value="#{bundle.EditAsignatureLabel_userId}" for="userId" />
                        <p:selectOneMenu id="userId" value="#{asignatureController.selected.userId}" required="true" requiredMessage="#{bundle.EditAsignatureRequiredMessage_userId}">
                            <f:selectItem itemLabel="#{bundle.SelectOneMessage}"/>
                            <f:selectItems value="#{userController.itemsAvailableSelectOne}"
                                           var="userIdItem"
                                           itemValue="#{userIdItem}"/>
                        </p:selectOneMenu>
                    </p:panelGrid>
                    <p:commandButton actionListener="#{asignatureController.update()}" value="#{bundle.Save}" update="display,:AsignatureListForm:datalist,:growl" oncomplete="handleSubmit(args, 'AsignatureEditDialog');"/>
                    <p:commandButton value="#{bundle.Cancel}" onclick="AsignatureEditDialog.hide()"/>
                </h:panelGroup>
            </h:form>
        </p:dialog>

    </ui:composition>
</html>

todoAgil-web/src/main/webapp/asignature/List.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <ui:composition template="/template.xhtml">


        <ui:define name="title">
            <h:outputText value="Lista de Asignaturas"></h:outputText>
        </ui:define>

        <ui:define name="body">
            <h:form id="AsignatureListForm">
                <p:panel header="Lista de Asignaturas">
                    <p:dataTable id="datalist" value="#{asignatureController.items}" var="item"
                                 selectionMode="single" selection="#{asignatureController.selected}"
                                 paginator="true"
                                 rowKey="#{item.asignatureId}"
                                 rows="10"
                                 rowsPerPageTemplate="10,20,30,40,50"
                                 >

                        <p:ajax event="rowSelect"   update="createButton viewButton editButton deleteButton"/>
                        <p:ajax event="rowUnselect" update="createButton viewButton editButton deleteButton"/>

                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="ID"/>
                            </f:facet>
                            <h:outputText value="#{item.asignatureId}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="Nombre"/>
                            </f:facet>
                            <h:outputText value="#{item.asignatureName}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="Horas Teoría"/>
                            </f:facet>
                            <h:outputText value="#{item.asignatureTheoryHours}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="Horas Ejercicios"/>
                            </f:facet>
                            <h:outputText value="#{item.asignatureExercisesHours}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="Horas Laboratorio"/>
                            </f:facet>
                            <h:outputText value="#{item.asignatureLabHours}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="Semestre"/>
                            </f:facet>
                            <h:outputText value="#{item.asignatureSemester}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="Año"/>
                            </f:facet>
                            <h:outputText value="#{item.asignatureYear}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListAsignatureTitle_asignatureClose}"/>
                            </f:facet>
                            <h:outputText value="#{item.asignatureClose}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListAsignatureTitle_userId}"/>
                            </f:facet>
                            <h:outputText value="ID Usuario"/>
                        </p:column>
                        <f:facet name="footer">
                            <p:commandButton id="createButton" icon="ui-icon-plus"   value="#{bundle.Create}" actionListener="#{asignatureController.prepareCreate}" update=":AsignatureCreateForm" oncomplete="PF('AsignatureCreateDialog').show()"/>
                            <p:commandButton id="viewButton"   icon="ui-icon-search" value="#{bundle.View}" update=":AsignatureViewForm" oncomplete="PF('AsignatureViewDialog').show()" disabled="#{empty asignatureController.selected}"/>
                            <p:commandButton id="editButton"   icon="ui-icon-pencil" value="#{bundle.Edit}" update=":AsignatureEditForm" oncomplete="PF('AsignatureEditDialog').show()" disabled="#{empty asignatureController.selected}"/>
                            <p:commandButton id="deleteButton" icon="ui-icon-trash"  value="#{bundle.Delete}" actionListener="#{asignatureController.destroy}" update=":growl,datalist" disabled="#{empty asignatureController.selected}"/>
                        </f:facet>
                    </p:dataTable>
                </p:panel>
            </h:form>

            <ui:include src="Create.xhtml"/>
            <ui:include src="Edit.xhtml"/>
            <ui:include src="View.xhtml"/>
        </ui:define>
    </ui:composition>

</html>

todoAgil-web/src/main/webapp/asignature/View.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <ui:composition>

        <p:dialog id="AsignatureViewDlg" widgetVar="AsignatureViewDialog" modal="true" resizable="false" appendTo="@(body)" header="#{bundle.ViewAsignatureTitle}">
            <h:form id="AsignatureViewForm">
                <h:panelGroup id="display">
                    <p:panelGrid columns="2" rendered="#{asignatureController.selected != null}">
                        <h:outputText value="#{bundle.ViewAsignatureLabel_asignatureId}"/>
                        <h:outputText value="#{asignatureController.selected.asignatureId}" title="#{bundle.ViewAsignatureTitle_asignatureId}"/>
                        <h:outputText value="#{bundle.ViewAsignatureLabel_asignatureName}"/>
                        <h:outputText value="#{asignatureController.selected.asignatureName}" title="#{bundle.ViewAsignatureTitle_asignatureName}"/>
                        <h:outputText value="#{bundle.ViewAsignatureLabel_asignatureTheoryHours}"/>
                        <h:outputText value="#{asignatureController.selected.asignatureTheoryHours}" title="#{bundle.ViewAsignatureTitle_asignatureTheoryHours}"/>
                        <h:outputText value="#{bundle.ViewAsignatureLabel_asignatureExercisesHours}"/>
                        <h:outputText value="#{asignatureController.selected.asignatureExercisesHours}" title="#{bundle.ViewAsignatureTitle_asignatureExercisesHours}"/>
                        <h:outputText value="#{bundle.ViewAsignatureLabel_asignatureLabHours}"/>
                        <h:outputText value="#{asignatureController.selected.asignatureLabHours}" title="#{bundle.ViewAsignatureTitle_asignatureLabHours}"/>
                        <h:outputText value="#{bundle.ViewAsignatureLabel_asignatureSemester}"/>
                        <h:outputText value="#{asignatureController.selected.asignatureSemester}" title="#{bundle.ViewAsignatureTitle_asignatureSemester}"/>
                        <h:outputText value="#{bundle.ViewAsignatureLabel_asignatureYear}"/>
                        <h:outputText value="#{asignatureController.selected.asignatureYear}" title="#{bundle.ViewAsignatureTitle_asignatureYear}"/>
                        <h:outputText value="#{bundle.ViewAsignatureLabel_asignatureClose}"/>
                        <h:outputText value="#{asignatureController.selected.asignatureClose}" title="#{bundle.ViewAsignatureTitle_asignatureClose}"/>
                        <h:outputText value="#{bundle.ViewAsignatureLabel_userId}"/>
                        <h:outputText value="#{asignatureController.selected.userId}" title="#{bundle.ViewAsignatureTitle_userId}"/>
                    </p:panelGrid>
                    <p:commandButton value="#{bundle.Close}" onclick="AsignatureViewDialog.hide()"/>
                </h:panelGroup>
            </h:form>
        </p:dialog>

    </ui:composition>
</html>