todoAgil-web/src/main/resources/cl/trello4/model/Action.java
package cl.trello4.model;

import java.util.Date;

/**
 * Model that represents a user action @ Trello.
 * <p/>
 * Example json:
 * <p/>
 * <code>
 * {
 * "id":"4f7f3809301cb98a5346bb50",
 * "idMemberCreator":"4f7d84acffdbe931585331bd",
 * "data":{
 * "text":"Adn can you make the checklists appear in the order I want and not in alphabetical order...",
 * "board":{
 * "name":"Trello Development",
 * "id":"4d5ea62fd76aa1136000000c"
 * },
 * "card":{
 * "name":"Assign people and due dates to specific checklist items.",
 * "id":"4f455a15dfe503f23316557f"
 * }
 * },
 * "type":"commentCard",
 * "date":"2012-04-06T18:38:01.791Z",
 * "memberCreator":{
 * "id":"4f7d84acffdbe931585331bd",
 * "username":"foobar",
 * "fullName":"Foo Bar",
 * "initials":"FB"
 * }
 * }
 * </code>
 *
 * @author joel
 */
public class Action extends TrelloObject {

    private String idMemberCreator;
    private String type;
    private Date date;
    private Member memberCreator;
    private Data data;

    public String getIdMemberCreator() {
        return idMemberCreator;
    }

    public void setIdMemberCreator(String idMemberCreator) {
        this.idMemberCreator = idMemberCreator;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public Date getDate() {
        return date;
    }

    public void setDate(Date date) {
        this.date = date;
    }

    public Member getMemberCreator() {
        return memberCreator;
    }

    public void setMemberCreator(Member memberCreator) {
        this.memberCreator = memberCreator;
    }

    public Data getData() {
        return data;
    }

    public void setData(Data data) {
        this.data = data;
    }

    public class Data {

        private String text;
        private Board board;
        private Card card;

        public String getText() {
            return text;
        }

        public void setText(String text) {
            this.text = text;
        }

        public Board getBoard() {
            return board;
        }

        public void setBoard(Board board) {
            this.board = board;
        }

        public Card getCard() {
            return card;
        }

        public void setCard(Card card) {
            this.card = card;
        }
    }


    public static class TYPE {

        public static final String CREATE_CARD = "createCard";
        public static final String COMMENT_CARD = "commentCard";
        public static final String UPDATE_CARD = "updateCard";
        public static final String UPDATE_CARD_ID_LIST = "updateCard:idList";
        public static final String UPDATE_CARD_CLOSED = "updateCard:closed";
        public static final String UPDATE_CARD_DESC = "updateCard:desc";
        public static final String UPDATE_CARD_NAME = "updateCard:name";
        public static final String ADD_MEMBER_TO_CARD = "addMemberToCard";
        public static final String REMOVE_MEMBER_FROM_CARD = "removeMemberFromCard";
        public static final String UPDATE_CHECK_ITEM = "updateCheckItemStateOnCard";
        public static final String ADD_ATTACHMENT = "addAttachmentToCard";
        public static final String REMOVE_ATTACHMENT = "removeAttachmentFromCard";
        public static final String ADD_CHECKLIST = "addChecklistToCard";
        public static final String REMOVE_CHECKLIST = "removeChecklistFromCard";
        public static final String CREATE_LIST = "createList";
        public static final String UPDATE_LIST = "updateList";
        public static final String CREATE_BOARD = "createBoard";
        public static final String UPDATE_BOARD = "updateBoard";
        public static final String ADD_MEMBER_TO_BOARD = "addMemberToBoard";
        public static final String REMOVE_MEMBER_FROM_BOARD = "removeMemberFromBoard";
        public static final String ADD_TO_ORGANIZATION_BOARD = "addToOrganizationBoard";
        public static final String REMOVE_FROM_ORGANIZATION_BOARD = "removeFromOrganizationBoard";
        public static final String CREATE_ORGANIZATION = "createOrganization";
        public static final String UPDATE_ORGANIZATION = "updateOrganization";

    }

}

todoAgil-web/src/main/resources/cl/trello4/model/Board.java
package cl.trello4.model;


public class Board extends TrelloObject {

	public enum PERMISSION_TYPE {
		PUBLIC, 
		ORGANIZATION,
		MEMBERS
	}

	private String name;
	private String desc;
	private boolean closed;
	private boolean invited = false;
	private String idOrganization;
	private String url;
	private Prefs prefs;

	
	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDesc() {
		return desc;
	}

	public void setDesc(String desc) {
		this.desc = desc;
	}

	public String getIdOrganization() {
		return idOrganization;
	}

	public void setIdOrganization(String idOrganization) {
		this.idOrganization = idOrganization;
	}

	public boolean isClosed() {
		return closed;
	}

	public void setClosed(boolean closed) {
		this.closed = closed;
	}

	public String getUrl() {
		return url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public Prefs getPrefs() {
		return prefs;
	}

	public void setPrefs(Prefs prefs) {
		this.prefs = prefs;
	}

	public boolean isInvited() {
		return invited;
	}

	public void setInvited(boolean invited) {
		this.invited = invited;
	}

	public class Prefs {

		private PERMISSION_TYPE voting;
		private PERMISSION_TYPE permissionLevel;
		private PERMISSION_TYPE invitations;
		private PERMISSION_TYPE comments;

        public PERMISSION_TYPE getVoting() {
			return voting;
		}

		public void setVoting(PERMISSION_TYPE voting) {
			this.voting = voting;
		}

		public PERMISSION_TYPE getPermissionLevel() {
			return permissionLevel;
		}

		public void setPermissionLevel(PERMISSION_TYPE permissionLevel) {
			this.permissionLevel = permissionLevel;
		}

		public PERMISSION_TYPE getInvitations() {
			return invitations;
		}

		public void setInvitations(PERMISSION_TYPE invitations) {
			this.invitations = invitations;
		}

		public PERMISSION_TYPE getComments() {
			return comments;
		}

		public void setComments(PERMISSION_TYPE comments) {
			this.comments = comments;
		}

	}
}

todoAgil-web/src/main/resources/cl/trello4/model/Card.java
package cl.trello4.model;

import java.util.Date;
import java.util.List;

public class Card extends TrelloObject {

	// TODO: idChecklists
	// TODO: checkItemStates
	// TODO: badges

	private String name;
	private String desc;
	private boolean closed;
	private Long idShort;
	private String idList;
	private String idBoard;
	private List<String> idMembers;
	private List<Attachment> attachments;
	private List<Label> labels;
	private String url;
	private double pos;

    public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDesc() {
		return desc;
	}

	public void setDesc(String desc) {
		this.desc = desc;
	}

	public boolean isClosed() {
		return closed;
	}

	public void setClosed(boolean closed) {
		this.closed = closed;
	}

	public Long getIdShort() {
		return idShort;
	}

	public void setIdShort(Long idShort) {
		this.idShort = idShort;
	}

	public String getIdList() {
		return idList;
	}

	public void setIdList(String idList) {
		this.idList = idList;
	}

	public String getIdBoard() {
		return idBoard;
	}

	public void setIdBoard(String idBoard) {
		this.idBoard = idBoard;
	}

	public List<String> getIdMembers() {
		return idMembers;
	}

	public void setIdMembers(List<String> idMembers) {
		this.idMembers = idMembers;
	}

	public String getUrl() {
		return url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public double getPos() {
		return pos;
	}

	public void setPos(double pos) {
		this.pos = pos;
	}

	public List<Attachment> getAttachments() {
		return attachments;
	}

	public void setAttachments(List<Attachment> attachments) {
		this.attachments = attachments;
	}

	public List<Label> getLabels() {
		return labels;
	}

	public void setLabels(List<Label> labels) {
		this.labels = labels;
	}

	public class Attachment {

		private String _id;
		private String bytes;
		private Date date;
		private String url;
		private String name;
		private String idMember;

		public String get_id() {
			return _id;
		}

		public void set_id(String _id) {
			this._id = _id;
		}

		public String getBytes() {
			return bytes;
		}

		public void setBytes(String bytes) {
			this.bytes = bytes;
		}

		public Date getDate() {
			return date;
		}

		public void setDate(Date date) {
			this.date = date;
		}

		public String getUrl() {
			return url;
		}

		public void setUrl(String url) {
			this.url = url;
		}

		public String getName() {
			return name;
		}

		public void setName(String name) {
			this.name = name;
		}

		public String getIdMember() {
			return idMember;
		}

		public void setIdMember(String idMember) {
			this.idMember = idMember;
		}
	}

	public class Label {

		private String color;
		private String name;

		public String getColor() {
			return color;
		}

		public void setColor(String color) {
			this.color = color;
		}

		public String getName() {
			return name;
		}

		public void setName(String name) {
			this.name = name;
		}
	}
}

todoAgil-web/src/main/java/managedbeans/AsignatureController.java
package managedbeans;

import cl.usach.diinf.todoagil.entities.Asignature;
import managedbeans.util.JsfUtil;
import managedbeans.util.JsfUtil.PersistAction;
import cl.usach.diinf.todoagil.facade.AsignatureFacadeLocal;

import java.io.Serializable;
import java.util.List;
import java.util.ResourceBundle;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.ejb.EJB;
import javax.ejb.EJBException;
import javax.inject.Named;
import javax.enterprise.context.SessionScoped;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.convert.Converter;
import javax.faces.convert.FacesConverter;

/**
 *
 * @author giovanni
 */
@Named("asignatureController")
@SessionScoped
public class AsignatureController implements Serializable {

    @EJB
    private cl.usach.diinf.todoagil.facade.AsignatureFacadeLocal ejbFacade;
    private List<Asignature> items = null;
    private Asignature selected;

    public AsignatureController() {
    }

    public Asignature getSelected() {
        return selected;
    }

    public void setSelected(Asignature selected) {
        this.selected = selected;
    }

    protected void setEmbeddableKeys() {
    }

    protected void initializeEmbeddableKey() {
    }

    private AsignatureFacadeLocal getFacade() {
        return ejbFacade;
    }

    public Asignature prepareCreate() {
        selected = new Asignature();
        initializeEmbeddableKey();
        return selected;
    }

    public void create() {
        persist(PersistAction.CREATE, ResourceBundle.getBundle("/Bundle").getString("AsignatureCreated"));
        if (!JsfUtil.isValidationFailed()) {
            items = null;    // Invalidate list of items to trigger re-query.
        }
    }

    public void update() {
        persist(PersistAction.UPDATE, ResourceBundle.getBundle("/Bundle").getString("AsignatureUpdated"));
    }

    public void destroy() {
        persist(PersistAction.DELETE, ResourceBundle.getBundle("/Bundle").getString("AsignatureDeleted"));
        if (!JsfUtil.isValidationFailed()) {
            selected = null; // Remove selection
            items = null;    // Invalidate list of items to trigger re-query.
        }
    }

    public List<Asignature> getItems() {
        if (items == null) {
            items = getFacade().findAll();
        }
        return items;
    }

    private void persist(PersistAction persistAction, String successMessage) {
        if (selected != null) {
            setEmbeddableKeys();
            try {
                if (persistAction != PersistAction.DELETE) {
                    getFacade().edit(selected);
                } else {
                    getFacade().remove(selected);
                }
                JsfUtil.addSuccessMessage(successMessage);
            } catch (EJBException ex) {
                String msg = "";
                Throwable cause = ex.getCause();
                if (cause != null) {
                    msg = cause.getLocalizedMessage();
                }
                if (msg.length() > 0) {
                    JsfUtil.addErrorMessage(msg);
                } else {
                    JsfUtil.addErrorMessage(ex, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
                }
            } catch (Exception ex) {
                Logger.getLogger(this.getClass().getName()).log(Level.SEVERE, null, ex);
                JsfUtil.addErrorMessage(ex, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
            }
        }
    }

    public Asignature getAsignature(java.lang.Integer id) {
        return getFacade().find(id);
    }

    public List<Asignature> getItemsAvailableSelectMany() {
        return getFacade().findAll();
    }

    public List<Asignature> getItemsAvailableSelectOne() {
        return getFacade().findAll();
    }

    @FacesConverter(forClass = Asignature.class)
    public static class AsignatureControllerConverter implements Converter {

        @Override
        public Object getAsObject(FacesContext facesContext, UIComponent component, String value) {
            if (value == null || value.length() == 0) {
                return null;
            }
            AsignatureController controller = (AsignatureController) facesContext.getApplication().getELResolver().
                    getValue(facesContext.getELContext(), null, "asignatureController");
            return controller.getAsignature(getKey(value));
        }

        java.lang.Integer getKey(String value) {
            java.lang.Integer key;
            key = Integer.valueOf(value);
            return key;
        }

        String getStringKey(java.lang.Integer value) {
            StringBuilder sb = new StringBuilder();
            sb.append(value);
            return sb.toString();
        }

        @Override
        public String getAsString(FacesContext facesContext, UIComponent component, Object object) {
            if (object == null) {
                return null;
            }
            if (object instanceof Asignature) {
                Asignature o = (Asignature) object;
                return getStringKey(o.getAsignatureId());
            } else {
                Logger.getLogger(this.getClass().getName()).log(Level.SEVERE, "object {0} is of type {1}; expected type: {2}", new Object[]{object, object.getClass().getName(), Asignature.class.getName()});
                return null;
            }
        }

    }

}

todoAgil-web/src/main/java/managedbeans/TrelloController.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package managedbeans;

import cl.trello4.model.Board;
import cl.trello4.model.Card;
import cl.trello4j.Trello;
import cl.trello4j.TrelloImpl;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.enterprise.context.SessionScoped;
import javax.inject.Named;
import org.primefaces.model.DualListModel;

@Named("trelloController")
@SessionScoped
public class TrelloController implements Serializable {

    static Trello trello = new TrelloImpl("d269beaefe036e410f090f10941b5d08", "5eef872dcf4b664c85593f6c7a9327608d8a47754362add1dc4b95ac98645c2b");

    private String board;
    int boardId;
    private String boardSeleccionada;
    boolean render = false;

    public String getBoardSeleccionada() {
        return boardSeleccionada;
    }

    public void setBoardSeleccionada(String boardSeleccionada) {
        this.boardSeleccionada = boardSeleccionada;
    }

    public String getBoard() {
        System.out.println("Hola");
        return board;
    }

    public List<Card> getCards() {
        List<Card> cards = trello.getCardsByBoard(board);
        return cards;
    }

    public void setBoard(String board) {
        System.out.println("CHAO");
        this.board = board;
    }

    public int getBoardId() {
        return boardId;
    }

    public void setBoardId(int boardId) {
        this.boardId = boardId;
    }

    public boolean isRender() {
        return render;
    }
    
    public List<Card> getCardsByBoardId() {
        this.render = false;
        if (this.boardSeleccionada == null) {
            List<Card> lista = null;
            return lista;
        } else {
            this.render = true;
            return trello.getCardsByBoard(this.boardSeleccionada);
        }
    }

    public String hola() {
        List<Board> org = trello.getBoardsByMember("me");
        return trello.getMember("me").getFullName();
    }

    public List<Board> getAllBoards() {
        return trello.getBoardsByMember("me");
    }

    public DualListModel<String> getAllBoardsString() {
        List<String> no_linked = new ArrayList<>();
        List<String> nombres = new ArrayList<>();
        List<Board> boards = trello.getBoardsByMember("me");
        for (int i = 0; i < boards.size(); i++) {
            no_linked.add(boards.get(i).getName());
//            nombres.add(boards.get(i).getName());
        }
        return new DualListModel<String>(no_linked, nombres);
    }
}

todoAgil-web/src/main/webapp/index.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" 
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      >
    <h:head>
        <title>index.xhtml</title>
        <h:outputStylesheet name="css/jsfcrud.css"/>
        <script src="http://code.jquery.com/jquery-1.7.1.min.js"></script>
        <script src="https://api.trello.com/1/client.js?key=d269beaefe036e410f090f10941b5d08&amp;token="></script>
        <script src="trello.js"></script>
        <!-- Latest compiled and minified CSS -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css" />

        <!-- Optional theme -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css" />

        <!-- Latest compiled and minified JavaScript -->
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
        <link href="style.css" />
        <style>
            #output{
                padding: 0 20px;
            }
        </style>
    </h:head>

    <h:body>
        <br />
        <h:link outcome="/asignature/List.xhtml" value="Mostrar las asignaturas"/>
        <br />
    </h:body>
</html>

todoAgil-web/src/main/webapp/prueba.jsp
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" 
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      >
    <h:head>
        <title>index.xhtml</title>
    </h:head>

    <h:body>

        <h1>JSF 2.0 View Data From The Database Table Example</h1>

        <h:dataTable value="#{usuarioBean.getUserList()}" var="u" border="1">

            <h:column>
                <f:facet name="header">
                    User ID
                </f:facet>
                #{u.userID}
            </h:column>

            <h:column>
                <f:facet name="header">
                    Name
                </f:facet>
                #{u.name}
            </h:column>

            <h:column>
                <f:facet name="header">
                    Address
                </f:facet>
                #{u.address}
            </h:column>

            <h:column>
                <f:facet name="header">
                    Created Date
                </f:facet>
                #{u.created_date}
            </h:column>

        </h:dataTable>

    </h:body>

</html>

todoAgil-web/src/main/webapp/prueba.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" 
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      >
    <h:head>
        <title>index.xhtml</title>
    </h:head>

    <h:body>

        <h1>Usuarios</h1>
        {usuarioBean.chao}
        <h:dataTable value="#{usuarioBean.userList}" var="user">
            #{user.userName + "Hola"}
        </h:dataTable>
        
        <h:dataTable value="#{usuarioBean.userList}" var="u">

            <h:column>
                <f:facet name="header">User ID</f:facet>
                #{u.userName}
            </h:column>

        </h:dataTable>

    </h:body>

</html>

todoAgil-web/src/main/webapp/template.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:p="http://primefaces.org/ui">

    <h:head>
        <title><ui:insert name="title">Default Title</ui:insert></title>
        <h:outputStylesheet library="css" name="jsfcrud.css"/>
        <h:outputScript library="js" name="jsfcrud.js"/>
    </h:head>

    <h:body>

        <p:growl id="growl" life="3000" />

        <p:layout fullPage="true">
            <p:layoutUnit position="north" size="65" header="#{bundle.AppName}">
                <h:form id="menuForm">
                    <p:menubar>
                        <p:menuitem value="Inicio" outcome="/index" icon="ui-icon-home"/>
                    </p:menubar>
                </h:form>
            </p:layoutUnit>

            <p:layoutUnit position="south" size="60">
                <ui:insert name="footer"/>
            </p:layoutUnit>

            <p:layoutUnit position="center">
                <ui:insert name="body"/>
            </p:layoutUnit>

        </p:layout>

    </h:body>

</html>

todoAgil-web/src/main/webapp/trello.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui"
      xmlns:c="http://xmlns.jcp.org/jsp/jstl/core"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets">
    <h:head>
        <title>Facelet Title</title>
    </h:head>
    <h:body>
        <h:form>
            <h:panelGrid columns="2" style="margin-bottom:10px" cellpadding="5" columnClasses="label, value">
                <p:outputLabel for="basic" value="Basic:" />
                <p:selectOneListbox id="basic" value="#{trelloController.boardSeleccionada}">
                    <f:selectItems value="#{trelloController.allBoards}" var="board" itemValue="#{board.id}" itemLabel="#{board.name}" />
                </p:selectOneListbox>
            </h:panelGrid>

            <p:separator />

            <p:commandButton widgetVar="boton" value="Submit" update="display"/>

            <p:panel id="display" widgetVar="resultados" closable="true" toggleable="true">
                <h:dataTable value="#{trelloController.getCardsByBoardId()}" var="card">
                    <h:column>#{card.name}</h:column>
                </h:dataTable>
            </p:panel>

            <p:dialog header="Selected Values" modal="true" showEffect="fade" widgetVar="dlg" resizable="false">

            </p:dialog>
        </h:form>
    </h:body>
</html>

todoAgil-web/src/main/webapp/welcomePrimefaces.xhtml
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:p="http://primefaces.org/ui">

    <f:view contentType="text/html">
        <h:head>
            <f:facet name="first">
                <meta content='text/html; charset=UTF-8' http-equiv="Content-Type"/>
                <title>Gio - PrimeFaces</title>
            </f:facet>
        </h:head>

        <h:body>

            <p:layout fullPage="true">

                <p:layoutUnit position="north" size="100" resizable="true" closable="true" collapsible="true">
                    Header
                </p:layoutUnit>

                <p:layoutUnit position="south" size="100" closable="true" collapsible="true">
                    Footer
                </p:layoutUnit>

                <select name="Hola">
                    <option ></option>
                    <option></option>
                </select>
                
                <p:layoutUnit position="west" size="175" header="Left" collapsible="true">
                    <p:menu>
                        <p:submenu label="Resources">
                            <p:menuitem value="Demo" url="http://www.primefaces.org/showcase-labs/ui/home.jsf" />
                            <p:menuitem value="Documentation" url="http://www.primefaces.org/documentation.html" />
                            <p:menuitem value="Forum" url="http://forum.primefaces.org/" />
                            <p:menuitem value="Themes" url="http://www.primefaces.org/themes.html" />

                        </p:submenu>

                    </p:menu>
                </p:layoutUnit>

               
                </p:layoutUnit>

            </p:layout>

        </h:body>

    </f:view>
</html>